-- 코드를 입력하세요
-- SELECT * FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY order by car_id;

SELECT CAR_ID, CASE WHEN SUM(START_DATE<='2022-10-16' and END_DATE>='2022-10-16')>=1 THEN '대여중'
ELSE '대여 가능' END as 'AVAILABILITY'
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
GROUP BY CAR_ID
order by CAR_ID desc;