-- 코드를 입력하세요
SELECT MONTH(START_DATE) as 'MONTH', CAR_ID, count(*) as 'RECORDS'
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
WHERE CAR_ID IN (SELECT CAR_ID  FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
                WHERE START_DATE>='2022-08-01' AND START_DATE<='2022-10-31'
                group by CAR_ID
                having count(*) >= 5)
AND YEAR(START_DATE)='2022' AND MONTH(START_DATE)>='8' AND MONTH(START_DATE)<='10'
group by MONTH,CAR_ID
ORDER BY MONTH asc, CAR_ID desc;