SELECT FI.ID as 'ID', FNI.FISH_NAME as 'FISH_NAME', FI.LENGTH as 'LENGTH'
FROM FISH_INFO FI 
JOIN FISH_NAME_INFO FNI
ON FI.FISH_TYPE = FNI.FISH_TYPE
WHERE (FI.FISH_TYPE,FI.LENGTH) IN (SELECT FISH_TYPE,MAX(LENGTH)
                                   FROM FISH_INFO
                                   GROUP BY FISH_TYPE)
order by FI.ID